version: 1

build_arg_defaults:
  EE_BASE_IMAGE: "registry.redhat.io/ansible-automation-platform-21/ee-supported-rhel8:1.0.1-88"
  # EE_BUILDER_IMAGE: "quay.io/mfordredhat/ansible-builder-rhel8:latest"
  EE_BUILDER_IMAGE: "registry.redhat.io/ansible-automation-platform-22/ansible-builder-rhel8:1.1.0-46"

ansible_config: 'ansible.cfg'  

dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt

additional_build_steps:
  append: |

    RUN wget https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip -P /build
    RUN unzip /build/awscli-exe-linux-x86_64.zip -d /build
    RUN rm /build/awscli-exe-linux-x86_64.zip
    RUN /build/aws/install
