version: 1

build_arg_defaults:
  EE_BASE_IMAGE: "registry.redhat.io/ansible-automation-platform-21/ee-supported-rhel8:latest"
  EE_BUILDER_IMAGE: "quay.io/ansible/ansible-builder:latest"
  #EE_BUILDER_IMAGE: "registry.redhat.io/ansible-automation-platform-22/ansible-builder:latest"

ansible_config: 'ansible.cfg'  

dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt
