---
collections:
  - name: google.cloud
    version: 1.0.2
  - name: amazon.aws
    version: 4.0.0
  - name: community.aws
    version: 4.0.0
  - name: servicenow.itsm
    version: 1.4.0
  - name: community.general
    version: 5.3.0
  - name: containers.podman
    version: 1.9.4
  - name: ansible.posix
    version: 1.4.0
  - name: ansible.controller
    version: 4.2.0
  

