---
collections:
  - name: community.general
    version: 5.7.0
  - name: community.vmware
    version: 2.9.1
  - name: community.windows
    version: 1.11.0
  - name: ansible.windows
    version: 1.11.1
  - name: community.aws
    version: 4.2.0
  - name: amazon.aws
    version: 4.2.0
  - name: azure.azcollection
    version: 1.13.0
  


